frontend:
  dist_path: ../frontend/dist
model:
  compute_type: int8
  device: cuda
  download_root: ./models
  hf_endpoint: https://hf-mirror.com
  model_path: large-v3
server:
  host: 0.0.0.0
  port: 9765
transcription:
  buffer_threshold: 2
  language: zh
  vad_filter: true
